### ISSUE TITLE
AADSTS53003 error related to Conditional Access Policy(CAP) isn't registred as a successful spray

### ISSUE THREAD

**Issue by alecmoran1** [knavesec/CredMaster#67]
Hi, Thank you so much for your great work on this tool. I have been using it for the last 2 years and loving the work! Unfortunately, when spraying o365 the following error doesn't result in a successful spray and shows it as a failure:

AADSTS53003  Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

Appreciate it if you don't mind updating the repo to reflect this change :)

**Comment by knavesec** [comment]
Hey @alecmoran1 thanks for the issue submission! Is this is in the `o365` module specifically or is it in any of the managed sprayers (`msol`, `azgraph`, `azvault`, `azuresso`)

If its the former, unfortunately the `o365` module is dead due to MS, see issue #68. If it's in the latter, we can update it or you could potentially submit a PR if desired :)

**Comment by knavesec** [comment]
@alecmoran1 following back up on this

**Comment by knavesec** [comment]
Closed in commit [7d9d1ae](https://github.com/knavesec/CredMaster/commit/7d9d1ae449f383805ed2158840d936f4f9b9ed71)
